// Mocks generated by Mockito 5.0.16 from annotations
// in linkedin_login/test/unit/utils/shared_mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i13;

import 'package:http/http.dart' as _i6;
import 'package:linkedin_login/src/DAL/api/linked_in_api.dart' as _i4;
import 'package:linkedin_login/src/DAL/repo/authorization_repository.dart'
    as _i2;
import 'package:linkedin_login/src/DAL/repo/user_repository.dart' as _i3;
import 'package:linkedin_login/src/model/linked_in_user_model.dart' as _i7;
import 'package:linkedin_login/src/utils/configuration.dart' as _i5;
import 'package:linkedin_login/src/utils/startup/graph.dart' as _i10;
import 'package:linkedin_login/src/wrappers/authorization_code_response.dart'
    as _i8;
import 'package:linkedin_login/src/wrappers/linked_in_token_object.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthorizationRepository_0 extends _i1.Fake
    implements _i2.AuthorizationRepository {}

class _FakeUserRepository_1 extends _i1.Fake implements _i3.UserRepository {}

class _FakeLinkedInApi_2 extends _i1.Fake implements _i4.LinkedInApi {}

class _FakeConfig_3 extends _i1.Fake implements _i5.Config {}

class _FakeClient_4 extends _i1.Fake implements _i6.Client {}

class _FakeLinkedInUserModel_5 extends _i1.Fake
    implements _i7.LinkedInUserModel {}

class _FakeAuthorizationCodeResponse_6 extends _i1.Fake
    implements _i8.AuthorizationCodeResponse {}

class _FakeLinkedInTokenObject_7 extends _i1.Fake
    implements _i9.LinkedInTokenObject {}

class _FakeLinkedInProfileEmail_8 extends _i1.Fake
    implements _i7.LinkedInProfileEmail {}

class _FakeResponse_9 extends _i1.Fake implements _i6.Response {}

class _FakeStreamedResponse_10 extends _i1.Fake
    implements _i6.StreamedResponse {}

/// A class which mocks [Graph].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGraph extends _i1.Mock implements _i10.Graph {
  MockGraph() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthorizationRepository get authorizationRepository =>
      (super.noSuchMethod(Invocation.getter(#authorizationRepository),
              returnValue: _FakeAuthorizationRepository_0())
          as _i2.AuthorizationRepository);
  @override
  _i3.UserRepository get userRepository =>
      (super.noSuchMethod(Invocation.getter(#userRepository),
          returnValue: _FakeUserRepository_1()) as _i3.UserRepository);
  @override
  _i4.LinkedInApi get api => (super.noSuchMethod(Invocation.getter(#api),
      returnValue: _FakeLinkedInApi_2()) as _i4.LinkedInApi);
  @override
  _i5.Config get linkedInConfiguration =>
      (super.noSuchMethod(Invocation.getter(#linkedInConfiguration),
          returnValue: _FakeConfig_3()) as _i5.Config);
  @override
  _i6.Client get httpClient =>
      (super.noSuchMethod(Invocation.getter(#httpClient),
          returnValue: _FakeClient_4()) as _i6.Client);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LinkedInApi get api => (super.noSuchMethod(Invocation.getter(#api),
      returnValue: _FakeLinkedInApi_2()) as _i4.LinkedInApi);
  @override
  _i11.Future<_i7.LinkedInUserModel> fetchFullProfile(
          {_i9.LinkedInTokenObject? token,
          List<String>? projection,
          _i6.Client? client}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchFullProfile, [],
                  {#token: token, #projection: projection, #client: client}),
              returnValue: Future<_i7.LinkedInUserModel>.value(
                  _FakeLinkedInUserModel_5()))
          as _i11.Future<_i7.LinkedInUserModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthorizationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthorizationRepository extends _i1.Mock
    implements _i2.AuthorizationRepository {
  MockAuthorizationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LinkedInApi get api => (super.noSuchMethod(Invocation.getter(#api),
      returnValue: _FakeLinkedInApi_2()) as _i4.LinkedInApi);
  @override
  _i11.Future<_i8.AuthorizationCodeResponse> fetchAccessTokenCode(
          {String? redirectedUrl,
          String? clientSecret,
          String? clientId,
          String? clientState,
          _i6.Client? client}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAccessTokenCode, [], {
                #redirectedUrl: redirectedUrl,
                #clientSecret: clientSecret,
                #clientId: clientId,
                #clientState: clientState,
                #client: client
              }),
              returnValue: Future<_i8.AuthorizationCodeResponse>.value(
                  _FakeAuthorizationCodeResponse_6()))
          as _i11.Future<_i8.AuthorizationCodeResponse>);
  @override
  _i8.AuthorizationCodeResponse fetchAuthorizationCode(
          {String? redirectedUrl, String? clientState}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAuthorizationCode, [],
                  {#redirectedUrl: redirectedUrl, #clientState: clientState}),
              returnValue: _FakeAuthorizationCodeResponse_6())
          as _i8.AuthorizationCodeResponse);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LinkedInApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkedInApi extends _i1.Mock implements _i4.LinkedInApi {
  MockLinkedInApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i9.LinkedInTokenObject> login(
          {String? redirectUrl,
          String? authCode,
          String? clientSecret,
          String? clientId,
          _i6.Client? client}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [], {
                #redirectUrl: redirectUrl,
                #authCode: authCode,
                #clientSecret: clientSecret,
                #clientId: clientId,
                #client: client
              }),
              returnValue: Future<_i9.LinkedInTokenObject>.value(
                  _FakeLinkedInTokenObject_7()))
          as _i11.Future<_i9.LinkedInTokenObject>);
  @override
  String takeUrl(String? value) =>
      (super.noSuchMethod(Invocation.method(#takeUrl, [value]), returnValue: '')
          as String);
  @override
  _i11.Future<_i7.LinkedInUserModel> fetchProfile(
          {String? token, List<String>? projection, _i6.Client? client}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchProfile, [],
                  {#token: token, #projection: projection, #client: client}),
              returnValue: Future<_i7.LinkedInUserModel>.value(
                  _FakeLinkedInUserModel_5()))
          as _i11.Future<_i7.LinkedInUserModel>);
  @override
  _i11.Future<_i7.LinkedInProfileEmail> fetchEmail(
          {String? token, _i6.Client? client}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchEmail, [], {#token: token, #client: client}),
          returnValue: Future<_i7.LinkedInProfileEmail>.value(
              _FakeLinkedInProfileEmail_8())) as _i11
          .Future<_i7.LinkedInProfileEmail>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i5.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get state =>
      (super.noSuchMethod(Invocation.getter(#state), returnValue: '')
          as String);
  @override
  String get initialUrl =>
      (super.noSuchMethod(Invocation.getter(#initialUrl), returnValue: '')
          as String);
  @override
  bool isCurrentUrlMatchToRedirection(String? url) => (super.noSuchMethod(
      Invocation.method(#isCurrentUrlMatchToRedirection, [url]),
      returnValue: false) as bool);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i6.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i12.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i12.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i12.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i12.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_9()))
          as _i11.Future<_i6.Response>);
  @override
  _i11.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i11.Future<String>);
  @override
  _i11.Future<_i13.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i13.Uint8List>.value(_i13.Uint8List(0)))
          as _i11.Future<_i13.Uint8List>);
  @override
  _i11.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future<_i6.StreamedResponse>.value(
                  _FakeStreamedResponse_10()))
          as _i11.Future<_i6.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
